const de: any = {
    English: 'Englisch',
    French: 'Französisch',
    Deutsch: 'Deutsch',
    'Add a price': 'Preis hinzufügen',
    'One time payment': 'Einmalzahlung',
    Monthly: 'Monatlich',
    Weeky: 'Wöchentlich',
    Daily: 'Täglich',
    Bookings: 'Buchungen',
    'What are the addresses for the relocation ?': 'Was sind die Adressen für den Umzug?',
    Details: 'Details',
    'Add disponibility': 'Verfügbarkeit hinzufügen',
    Clients: 'Kunden',
    Revenue: 'Einnahmen',
    'Revenue by method': 'Einnahmen nach Methode',
    PayPal: 'PayPal',
    Stripe: 'Stripe',
    Payments: 'Zahlungen',
    Settings: 'Einstellungen',
    'Rate per hour': 'Stundensatz',
    'Rate per worker': 'Preis pro Arbeiter',
    'Rate per Vehicle': 'Preis pro Fahrzeug',
    'Save changes': 'Änderungen speichern',
    'My bookings': 'Meine Buchungen',
    'Welcome back': 'Willkommen zurück',
    'Connect to your account and manage your bookings': 'Melden Sie sich bei Ihrem Konto an und verwalten Sie Ihre Buchungen',
    'Email address': 'E-Mail-Adresse',
    Password: 'Passwort',
    'Password forget ?': 'Passwort vergessen?',
    Yes: 'Ja',
    Login: 'Einloggen',
    'My messages': 'Meine Nachrichten',
    'My payments': 'Meine Zahlungen',
    'Processed At': 'Verarbeitet am',
    'Registered At': 'Registriert am',
    'Credit Card': 'Kreditkarte',
    'Mobile Money': 'Mobile Money',
    Pending: 'Ausstehend',
    Completed: 'Abgeschlossen',
    Failed: 'Fehlgeschlagen',
    'Date & Time': 'Datum & Uhrzeit',
    Origin: 'Abholort',
    Destination: 'Zielort',
    Workers: 'Arbeiter',
    Cars: 'Fahrzeuge',
    Duration: 'Dauer',
    Amount: 'Betrag',
    Observation: 'Bemerkung',
    'Optional notes': 'Optionale Notizen',
    'Duration (hours)': 'Dauer (Stunden)',

    'Select origin': 'Abholort auswählen',
    'Select destination': 'Zielort auswählen',

    'Create Booking': 'Buchung erstellen',
    'Edit Booking': 'Buchung bearbeiten',
    'Booking Details': 'Buchungsdetails',
    'Booking Information': 'Buchungsinformationen',

    'New Booking': 'Neue Buchung',

    // Booking form
    Cost: 'Kosten',
    Hours: 'Stunden',
    Vehicles: 'Fahrzeuge',
    'You paid': 'Sie haben bezahlt',
    'Book a relocation': 'Umzug buchen',
    prestation: 'Leistung',
    Locations: 'Standorte',
    'Date and time': 'Datum und Uhrzeit',
    Submission: 'Abgabe',
    Back: 'Zurück',
    Continue: 'Weiter',
    Submit: 'Absenden',
    'Delete Booking?': 'Buchung löschen?',
    'This action cannot be undone.': 'Diese Aktion kann nicht rückgängig gemacht werden.',
    workers: 'Arbeiter',
    Cancel: 'Abbrechen',
    Delete: 'Löschen',
    'When and at what time ?': 'Wann und um welche Uhrzeit?',
    'Provide detail about the prestation': 'Geben Sie Details zur Leistung an',
    'How many workers do you need?': 'Wie viele Arbeiter benötigen Sie?',
    'How long will the process take (in hours)?': 'Wie lange dauert der Prozess (in Stunden)?',
    'Does the process require vehicles?': 'Benötigt der Prozess Fahrzeuge?',
    'How many vehicles are needed?': 'Wie viele Fahrzeuge werden benötigt?',
    'What are the the addresses for the relocation ?': 'Welche Adressen gelten für den Umzug?',
    From: 'Von',
    To: 'Nach',
    Address: 'Adresse',
    'Your first name': 'Ihr Vorname',
    'Your last name': 'Ihr Nachname',
    'Your email': 'Ihre E-Mail',
    'Phone number': 'Telefonnummer',
    'Choose a password to access your account': 'Wählen Sie ein Passwort für den Zugriff auf Ihr Konto',
    // Home page
    'Book a prestation': 'Leistung buchen',
    Account: 'Konto',
    'The best move you': 'Der beste Umzug, den Sie',
    will: 'werden',
    'ever make': 'jemals machen',
    'We provide top-quality relocation services designed to ensure safety, efficiency, and complete client satisfaction — from careful handling of your belongings to seamless coordination at every stage of your move.':
        'Wir bieten hochwertige Umzugsdienstleistungen an, die Sicherheit, Effizienz und vollständige Kundenzufriedenheit gewährleisten – von der sorgfältigen Behandlung Ihres Eigentums bis zur nahtlosen Koordination in jeder Phase Ihres Umzugs.',
    'We move safely': 'Wir ziehen sicher um',
    'Safe moving': 'Sicherer Umzug',
    Procedures: 'Verfahren',
    'Make your': 'Machen Sie Ihre',
    reservation: 'Reservierung',
    'Explore featured': 'Entdecken Sie unsere Dienstleistungen',
    'Load your': 'Laden Sie Ihr',
    container: 'Container',
    'We will take it': 'Wir transportieren es',
    'from there': 'von dort',
    'Relocation Company': 'Umzugsunternehmen',
    'We give you complete': 'Wir geben Ihnen vollständige',
    'control of your shipment': 'Kontrolle über Ihre Sendung',
    'We ensure a smooth and stress-free moving experience through high-quality logistics, professional staff, and reliable coordination at every step of your relocation.':
        'Wir gewährleisten ein reibungsloses und stressfreies Umzugserlebnis durch hochwertige Logistik, professionelles Personal und zuverlässige Koordination in jeder Phase Ihres Umzugs.',
    'Innovative Systems': 'Innovative Systeme',
    'Our advanced tools, digital tracking, and modern logistics systems enhance efficiency and offer you complete visibility throughout the process.':
        'Unsere fortschrittlichen Tools, digitale Nachverfolgung und moderne Logistiksysteme steigern die Effizienz und bieten Ihnen vollständige Transparenz während des gesamten Prozesses.',
    'Best prices': 'Beste Preise',
    'We provide competitive and transparent pricing, ensuring excellent value without compromising the quality or safety of your move.':
        'Wir bieten wettbewerbsfähige und transparente Preise, die hervorragenden Wert bieten, ohne die Qualität oder Sicherheit Ihres Umzugs zu beeinträchtigen.',
    'Focus on quality': 'Fokus auf Qualität',
    'We provide the best services': 'Wir bieten die besten Dienstleistungen',
    'for your relocation': 'für Ihren Umzug',
    'Transparent pricing': 'Transparente Preisgestaltung',
    'Good Equipements': 'Gute Ausstattung',
    'Years of experiences': 'Jahre Erfahrung',
    'We are committed to delivering professional and reliable relocation services to all our clients.':
        'Wir verpflichten uns, allen unseren Kunden professionelle und zuverlässige Umzugsdienstleistungen zu bieten.',
    'Book a reservation': 'Reservierung buchen',
    'Login into account': 'Im Konto einloggen',
    'About Us': 'Über uns',
    Policy: 'Richtlinie',
    'Terms and conditions': 'Allgemeine Geschäftsbedingungen',
};

export default de;
