const fr: any = {
    English: 'Anglais',
    French: 'Français',
    Deutsch: 'Allemand',
    'What are the addresses for the relocation ?': 'Quelles sont les adresses pour le déménagement ?',
    Details: 'Détails',

    'Add a price': 'Ajouter un prix',
    'One time payment': 'Paiement unique',
    Monthly: 'Mensuel',
    Weeky: 'Hebdomadaire',
    Daily: 'Journalier',
    Bookings: 'Réservations',
    'Add disponibility': 'Ajouter une disponibilite',
    Clients: 'Clients',
    Revenue: 'Revenus',
    'Revenue by method': 'Revenus par méthode',
    PayPal: 'PayPal',
    Stripe: 'Stripe',
    Payments: 'Payments',
    Settings: 'Paramètres',
    'Rate per hour': 'Tarif par heure',
    'Rate per worker': 'Tarif par travailleur',
    'Rate per Vehicle': 'Tarif par véhicule',
    'Save changes': 'Enregistrer les modifications',
    'My bookings': 'Mes reversations',
    'Welcome back': 'Bon retour',
    'Connect to your account and manage your bookings': 'Connectez-vous à votre compte et gérez vos réservations',
    'Email address': 'Adresse e-mail',
    Password: 'Mot de passe',
    'Password forget ?': 'Mot de passe oublié ?',
    Yes: 'Oui',
    Login: 'Se connecter',
    'My messages': 'Mes messages',
    'My payments': 'Mes paiements',
    'Processed At': 'Traitée le',
    'Registered At': 'Enregistrée le',
    'Credit Card': 'Carte bancaire',
    'Mobile Money': 'Mobile Money',
    Pending: 'En attente',
    Completed: 'Complété',
    Failed: 'Échoué',
    'Date & Time': 'Date et heure',
    Origin: 'Origine',
    Destination: 'Destination',
    Workers: 'Ouvriers',
    Cars: 'Voitures',
    Duration: 'Durée',
    Amount: 'Montant',
    Observation: 'Observation',
    'Optional notes': 'Notes (facultatif)',
    'Duration (hours)': 'Durée (heures)',

    'Select origin': "Sélectionner l'origine",
    'Select destination': 'Sélectionner la destination',

    'Create Booking': 'Créer une réservation',
    'Edit Booking': 'Modifier la réservation',
    'Booking Details': 'Détails de la réservation',
    'Booking Information': 'Informations de réservation',

    'New Booking': 'Nouvelle réservation',

    // Booking form
    Cost: 'Coût',
    Hours: 'Heures',
    Vehicles: 'Véhicules',
    'You paid': 'Vous avez payé',
    'Book a relocation': 'Réserver un déménagement',
    prestation: 'prestation',
    Locations: 'Emplacements',
    'Date and time': 'Date et heure',
    Submission: 'Soumission',
    Back: 'Retour',
    Continue: 'Continuer',
    Submit: 'Soumettre',
    'Delete Booking?': 'Supprimer la réservation ?',
    'This action cannot be undone.': 'Cette action est irréversible.',
    workers: 'travailleurs',
    Cancel: 'Annuler',
    Delete: 'Supprimer',
    'When and at what time ?': 'Quand et à quelle heure ?',
    'Provide detail about the prestation': 'Fournir des détails sur la prestation',
    'How many workers do you need?': 'Combien de travailleurs avez-vous besoin ?',
    'How long will the process take (in hours)?': 'Combien de temps le processus peut-il prendre (en heures) ?',
    'Does the process require vehicles?': 'Le processus nécessite-t-il des véhicules ?',
    'How many vehicles are needed?': 'Combien de véhicules sont nécessaires ?',
    'What are the the addresses for the relocation ?': 'Quelles sont les adresses pour le déménagement ?',
    From: 'De',
    To: 'À',
    Address: 'Adresse',
    'Your first name': 'Votre prénom',
    'Your last name': 'Votre nom',
    'Your email': 'Votre e-mail',
    'Phone number': 'Numéro de téléphone',
    'Choose a password to access your account': 'Choisissez un mot de passe pour accéder à votre compte',
    // Home page,

    'Book a prestation': 'Réserver une prestation',
    Account: 'Compte',
    'The best move you': 'Le meilleur déménagement que vous',
    will: 'allez',
    'ever make': 'jamais faire',
    'We provide top-quality relocation services designed to ensure safety, efficiency, and complete client satisfaction — from careful handling of your belongings to seamless coordination at every stage of your move.':
        "Nous offrons des services de déménagement de haute qualité conçus pour assurer la sécurité, l'efficacité et une satisfaction complète du client — depuis la manipulation soigneuse de vos biens jusqu'à la coordination fluide à chaque étape de votre déménagement.",
    'We move safely': 'Nous déménageons en toute sécurité',
    'Safe moving': 'Déménagement sécurisé',
    Procedures: 'Procédures',
    'Make your': 'Effectuez votre',
    reservation: 'réservation',
    'Explore featured': 'Découvrez nos services',
    'Load your': 'Chargez votre',
    container: 'conteneur',
    'We will take it': 'Nous le transporterons',
    'from there': 'de là',
    'Relocation Company': 'Entreprise de déménagement',
    'We give you complete': 'Nous vous offrons un contrôle complet',
    'control of your shipment': 'de votre expédition',
    'We ensure a smooth and stress-free moving experience through high-quality logistics, professional staff, and reliable coordination at every step of your relocation.':
        'Nous garantissons une expérience de déménagement fluide et sans stress grâce à une logistique de haute qualité, un personnel professionnel et une coordination fiable à chaque étape de votre déménagement.',
    'Innovative Systems': 'Systèmes innovants',
    'Our advanced tools, digital tracking, and modern logistics systems enhance efficiency and offer you complete visibility throughout the process.':
        "Nos outils avancés, le suivi numérique et les systèmes logistiques modernes améliorent l'efficacité et vous offrent une visibilité totale tout au long du processus.",
    'Best prices': 'Meilleurs prix',
    'We provide competitive and transparent pricing, ensuring excellent value without compromising the quality or safety of your move.':
        'Nous proposons des tarifs compétitifs et transparents, garantissant une excellente valeur sans compromettre la qualité ou la sécurité de votre déménagement.',
    'Focus on quality': "Mettre l'accent sur la qualité",
    'We provide the best services': 'Nous fournissons les meilleurs services',
    'for your relocation': 'pour votre déménagement',
    'Transparent pricing': 'Tarification transparente',
    'Good Equipements': 'Équipements de qualité',
    'Years of experiences': "Années d'expérience",
    'We are committed to delivering professional and reliable relocation services to all our clients.':
        'Nous nous engageons à fournir des services de déménagement professionnels et fiables à tous nos clients.',
    'Book a reservation': 'Réserver une prestation',
    'Login into account': 'Connexion au compte',
    'About Us': 'À propos de nous',
    Policy: 'Politique',
    'Terms and conditions': 'Conditions générales',
};

export default fr;
